[package]
name = "scratch-compiler-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-match = { path = "./fancy-match" }
trexp = { git = "https://github.com/Johan-Mi/trexp" }
sb3-stuff = { git = "https://github.com/Johan-Mi/sb3-stuff" }
md5 = "0.7.0"
nom = "7.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.80"
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
smol_str = "0.1"
codespan = { git = "https://github.com/Johan-Mi/codespan" }
codespan-reporting = { git = "https://github.com/Johan-Mi/codespan" }
phf = { version = "0.11.1", features = ["macros"] }
gumdrop = "0.8.1"
